# Copyright 2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "org.cloudfoundry.tomcat"
name = "Cloud Foundry Apache Tomcat Buildpack"
version = "1.0.0-BUILD-SNAPSHOT"

stacks = [
  { id = "io.buildpacks.stacks.bionic" },
  { id = "org.cloudfoundry.stacks.cflinuxfs3" },
]

[[metadata.dependencies]]
id      = "tomcat"
name    = "Apache Tomcat"
version = "7.0.94"
uri     = "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz"
sha256  = "4bf63feb6fa79602c2e6afdfec945c4b1b5b3e1f1ccb273c1b60be57a699278a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://www.apache.org/licenses/"

[[metadata.dependencies]]
id      = "tomcat"
name    = "Apache Tomcat"
version = "8.5.40"
uri     = "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz"
sha256  = "2c429a686feec086d654ac8a2b7df65a89f3b6017678c530d1ecedf35401e3d3"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://www.apache.org/licenses/"

[[metadata.dependencies]]
id      = "tomcat"
name    = "Apache Tomcat"
version = "9.0.18"
uri     = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.18/bin/apache-tomcat-9.0.18.tar.gz"
sha256  = "95bc1b85e8baa485f148ceeafd921f45e8b632891b31b2aa7199d839e203e619"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://www.apache.org/licenses/"

[metadata]
pre_package = "ci/build.sh"
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "buildpack.toml",
]
