kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: uaa
  name: fake-scope
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fake-rolebinding
  namespace: uaa
subjects:
- kind: Group
  name: foobar
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fake-scope
  apiGroup: rbac.authorization.k8s.io