apiVersion: v1
kind: Service
metadata:
  name: {{ include "uaa-k8srelease.fullname" . }}
  namespace: uaa
  labels:
{{ include "uaa-k8srelease.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "uaa-k8srelease.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
